### ISSUE TITLE
cache_expires_after doesn't work

### ISSUE THREAD

**Issue by antoniaettorre** [frmichel/sparql-micro-service#5]
The parameter cache_expires_after in config.ini file of the micro-service does not work: JSON documents are still retrieved from cache even if they should have expired.

**Comment by frmichel** [comment]
Date stored in cache was expiration date, therefore, changing the cache_expires_after parameter was not changed anything.
Changed this to store the fetch date, so that the expiration date is recomputed every time with the value of cache_expires_after.

Merged on branch master. To be included in version 0.3.2.
